name: FractalForest
version: 1.8.5
main: com.eclipsekingdom.fractalforest.FractalForest
api-version: 1.13
authors: [sword]
description: A spigot plugin that adds procedurally generated trees to Minecraft
website: eclipsekingdom.com
softdepend: [PlayerPlot, WorldGuard, RedProtect, Towny, CoreProtect, GriefPrevention, Residence, Civs]
load: POSTWORLD

commands:
  fractalforest:
    description: display plugin information
  sapling:
    description: summon a magic sapling
    permission: forest.sapling
  tpop:
    description: edit tree populators
    permission: forest.pop
  tgenerator:
    description: edit the tree generator
    permission: forest.gen
  tencyclopedia:
    description: request an encyclopedia
    permission: forest.encyclopedia
  updatetrecords:
    description: update the records in inventory
    permission: forest.encyclopedia
  giftsapling:
    description: gift a sapling to a player
    permission: forest.sapling


permissions:
  forest.*:
    description: grants all user
    default: op
  forest.sapling:
    description: grants access to sapling commands
    default: op
  forest.pop:
    description: grants access to tpop commands
    default: op
  forest.gen:
    description: grants access to /tgeneration
    default: op
  forest.encyclopedia:
    description: grants access to encyclopedia commands
    default: op